name: 自動化

on:
    schedule:
        - cron: "0 5,17 * * *"
    workflow_dispatch:

jobs:
    automation:
        name: 自動化
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - name: Bahamut Automation
              uses: JacobLinCool/Bahamut-Automation@v0.6.13
              with:
                  modules: "login,ad_handler,sign,answer,discord,lottery,logout,discord"
                  parameters: ${{ secrets.parameters || '{}' }}
                  secrets: ${{ secrets.secrets }}

            - uses: gautamkrishnar/keepalive-workflow@master
